### ISSUE TITLE
NoSuchMethodError in PlayJsonResultMarshaller while running graphql query

### ISSUE THREAD

**Issue by vivekdhayaal** [sangria-graphql/sangria-play-json#11]
after upgrading to sangria-play-json v1.0.3 and executing any graphQL query in a scala play app, "NoSuchMethodError" is thrown in PlayJsonResultMarshaller as seen in the stack track below:

Library upgrade info:
<pre>
 -    compile "org.sangria-graphql:sangria_2.11:1.3.3"
 -    compile "org.sangria-graphql:sangria-play-json_2.11:1.0.0"
 +    compile "org.sangria-graphql:sangria_2.11:1.4.2" 
 +    compile "org.sangria-graphql:sangria-play-json_2.11:1.0.3"
 +    compile "org.sangria-graphql:sangria-relay_2.11:1.4.2"
      compile "org.sangria-graphql:sangria-slowlog_2.11:0.1.4"
...
 +       force "org.sangria-graphql:sangria-marshalling-api_2.11:1.0.3"
 +       force "org.sangria-graphql:sangria_2.11:1.4.2"
</pre>

Error stack trace:
<pre>
Uncaught error from thread [application-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.NoSuchMethodError: play.api.libs.json.JsArray.<init>(Lscala/collection/IndexedSeq;)V
        at sangria.marshalling.playJson$PlayJsonResultMarshaller$.arrayNode(playJson.scala:18)
        at sangria.marshalling.playJson$PlayJsonResultMarshaller$.arrayNode(playJson.scala:8)
        at sangria.execution.ValueCoercionHelper.coerceInputValue(ValueCoercionHelper.scala:242)
[2018-09-26 17:29:51.820] [error] a.a.ActorSystemImpl [application-akka.actor.default-dispatcher-5] - Uncaught error from thread [application-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
        at sangria.execution.ValueCoercionHelper.coerceInputValue(ValueCoercionHelper.scala:225)
        at sangria.execution.ValueCoercionHelper$$anonfun$6.apply(ValueCoercionHelper.scala:270)
        at sangria.execution.ValueCoercionHelper$$anonfun$6.apply(ValueCoercionHelper.scala:266)
        at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
        at scala.collection.immutable.List.foldLeft(List.scala:84)
        at sangria.execution.ValueCoercionHelper.coerceInputValue(ValueCoercionHelper.scala:266)
        at sangria.execution.ValueCoercionHelper$$anonfun$3.apply(ValueCoercionHelper.scala:234)
        at sangria.execution.ValueCoercionHelper$$anonfun$3.apply(ValueCoercionHelper.scala:231)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.Iterator$class.foreach(Iterator.scala:742)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at sangria.execution.ValueCoercionHelper.coerceInputValue(ValueCoercionHelper.scala:231)
        at sangria.execution.ValueCoercionHelper.coerceInputValue(ValueCoercionHelper.scala:225)
        at sangria.execution.ValueCoercionHelper$$anonfun$6.apply(ValueCoercionHelper.scala:270)
        at sangria.execution.ValueCoercionHelper$$anonfun$6.apply(ValueCoercionHelper.scala:266)
        at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
        at scala.collection.immutable.List.foldLeft(List.scala:84)
        at sangria.execution.ValueCoercionHelper.coerceInputValue(ValueCoercionHelper.scala:266)
        at sangria.execution.ValueCollector$$anonfun$8$$anonfun$11.apply(ValueCollector.scala:91)
        at sangria.execution.ValueCollector$$anonfun$8$$anonfun$11.apply(ValueCollector.scala:91)
        at scala.Option.map(Option.scala:146)
        at sangria.execution.ValueCollector$$anonfun$8.apply(ValueCollector.scala:91)
        at sangria.execution.ValueCollector$$anonfun$8.apply(ValueCollector.scala:81)
        at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
        at scala.collection.immutable.List.foldLeft(List.scala:84)
        at sangria.execution.ValueCollector$.getArgumentValues(ValueCollector.scala:81)
        at sangria.execution.ValueCollector.getArgumentValues(ValueCollector.scala:53)
        at sangria.execution.ValueCollector$$anonfun$getFieldArgumentValues$1.apply(ValueCollector.scala:46)
        at sangria.execution.ValueCollector$$anonfun$getFieldArgumentValues$1.apply(ValueCollector.scala:46)
        at sangria.util.ConcurrentHashMapCache.getOrElseUpdate(ConcurrentHashMapCache.scala:29)
        at sangria.execution.ValueCollector.getFieldArgumentValues(ValueCollector.scala:46)
        at sangria.execution.Resolver.resolveField(Resolver.scala:962)
        at sangria.execution.Resolver$$anonfun$collectActionsPar$1.apply(Resolver.scala:445)
        at sangria.execution.Resolver$$anonfun$collectActionsPar$1.apply(Resolver.scala:439)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:155)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:155)
        at scala.collection.Iterator$class.foreach(Iterator.scala:742)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:155)
        at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
        at sangria.execution.Resolver.collectActionsPar(Resolver.scala:439)
        at sangria.execution.Resolver.resolveFieldsPar(Resolver.scala:45)
        at sangria.execution.Executor.sangria$execution$Executor$$executeOperation(Executor.scala:155)
        at sangria.execution.Executor$$anonfun$6$$anonfun$apply$9$$anonfun$apply$10$$anonfun$apply$11$$anonfun$apply$12.apply(Executor.scala:96)
        at sangria.execution.Executor$$anonfun$6$$anonfun$apply$9$$anonfun$apply$10$$anonfun$apply$11$$anonfun$apply$12.apply(Executor.scala:95)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at scala.concurrent.ExecutionContext$$anon$1.run
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
</pre>

**Comment by OlegIlyenko** [comment]
I just updated to the recent play-json version, would be great if you could check it https://github.com/sangria-graphql/sangria-play-json/releases/tag/v1.0.5
