### ISSUE TITLE
Broken with play 2.6.0-RC1

### ISSUE THREAD

**Issue by BowlingX** [sangria-graphql/sangria-play-json#5]
Play 2.6.0-RC1 (`play-json`) introduces a breaking change on `sangria-play-json` 1.0.1:

```
Caused by: java.lang.NoSuchMethodError: play.api.libs.json.JsArray.value()Lscala/collection/Seq;
        at sangria.marshalling.playJson$PlayJsonInputUnmarshaller$.getListValue(playJson.scala:53)
        at sangria.marshalling.playJson$PlayJsonInputUnmarshaller$.getListValue(playJson.scala:49)
        at sangria.execution.ValueCoercionHelper.isValidValue(ValueCoercionHelper.scala:338)
        at sangria.execution.ValueCoercionHelper.getVariableValue(ValueCoercionHelper.scala:408)
        at sangria.execution.ValueCollector.$anonfun$getVariableValues$2(ValueCollector.scala:28)
        at scala.Option.map(Option.scala:146)
```

**Comment by OlegIlyenko** [comment]
thanks for a reminder and PR! Just released **v1.0.2** with dep on play-json Play 2.6.0-RC2.
